### ISSUE TITLE
Need instruction to set device state and control the WLED system...

### ISSUE THREAD

**Issue by Pizzanomicon** [frenck/python-wled#1019]
# How do I set the device state?

> I would like to use this library to control my WLED device, but cannot find documentation on usage.

## Expected behavior

> I would like to find the command (likely AWAIT) to set/command it to switch to  {device.state.preset.name}, similar to how you have used:
` await led.master(on=True, brightness=64)`

## Actual behavior

>  All I see in the example is how to read {device.state.preset.name}, please help!  Thank you!

**Comment by frenck** [comment]
Use the segment() method, see online code documentation for references.

../Frenck
