### ISSUE TITLE
support for firmware on WLED_***_ESP32_audioreactive.bin

### ISSUE THREAD

**Issue by dgm** [frenck/python-wled#1345]
# Problem/Motivation
I'm not sure if Home Assistant relies on this library as a dependency, but the code here makes much more sense for generating the firmware download;   Since WLED posts a firmware version for audioreactive version, could we include that in the update logic as well, so it doesn't lose the audio reactive features when an update is applied?

## Expected behavior

New version of WLED_***_ESP32_audioreactive.bin  is updated

## Actual behavior

WLED_***_ESP32.bin is installed

## Steps to reproduce

Update an existing ESP32 with an audio reactive firmware installed.

## Proposed changes

I'm not fluent enough in python yet to know how to identify the audioreactive software .. if nothing else, is the config item for it verifiable?     Once identified a similar code path as used for the ethernet variant should work.

**Comment by frenck** [comment]
This has been resolved in #1646. When a WLED device reports its firmware release name (e.g. `ESP32_audioreactive`), the upgrade method now uses it to build the correct firmware filename instead of guessing from architecture alone.
