### ISSUE TITLE
Wrong LightCapability enum values

### ISSUE THREAD

**Issue by Suxsem** [frenck/python-wled#1366]
According to https://kno.wled.ge/interfaces/json-api/#light-capabilities, lc values are mapped as following:

- 0 => None
- 1 => RGB
- 2 => White channel
- 3 => RGBW
- 6 => CCT (White channel only)
- 7 => CCT + RGB
- others => unused / reserved

Values in the LightCapability enum seem to be wrong:
https://github.com/frenck/python-wled/blob/57d046c6c1806876466e7d22105a66c91ab71470/src/wled/const.py#L10-L25

**Comment by frenck** [comment]
To me it seems right? This is a bit map?

**Comment by Suxsem** [comment]
You are totally right, didn't see the IntFlag, sorry for the fuss, closing
