### ISSUE TITLE
WLED Integration requires internet connection?

### ISSUE THREAD

**Issue by RadianceNL** [frenck/python-wled#584]
Since yesterday my internet connection isn’t working anymore because failure from the ISP side.
That sucks but HA works locally too for, right?

Well actually I noticed all my WLED interfaces don’t work anymore through the Home Assistant integration.

The error message the integration gives is :Invalid response from API: Timeout occurred while communicating with GitHub for WLED version

The WLED instances are reachable through the local network to their IP addresses and the WLED app with the instances is working fine. When I click on a device in the HA integration I can also click the button ‘Go to device’ which points me to the actual device on my local network.

I’ve deleted one of the lights and tried to re add is but then I get an error that it’s unable to connect, which is strange because I can actually ping the instance from both the HA cli and the server HA is running on. (Proxmox server)

Previously WLED devices did work without an internet connection. When we moved last November we didn’t had an internet connection for a couple of days but through the local network I would still be able to manage my WLED instances.

Nothing changed in my local network except that I don’t have a WAN connection at the moment.

I can’t find any specific WLED errors in the logs either so that ain’t much helpful.

I understand that some API call require an internet connection but I don’t see why the basic functionality of a WLED integration requires an internet connection. Is this a bug or did something change recently or am I overseeing something?

**Comment by frenck** [comment]
This has been adjusted in the later versions of this library, which version are you on?

**Comment by RadianceNL** [comment]
Not sure how I can check what library version I am on but I'm still on HA 2021.12.10.
I see the PR is from January 13th so I guess it'll be fixed once I update.

Once my internet is fixed I'll update HA.

Thanks for the quick reply, issue can be closed. :-)

**Comment by chatziko** [comment]
Hello, this problem still appears with v0.13.0 (using the latest Home Assisant 2022.2.9). Without internet connection I get
```
Invalid response from API: Timeout occurred while communicating with GitHub for WLED version
```
I see 3 calls to `get_wled_versions_from_github`, two with `suppress(WLEDError)`, but one without:
https://github.com/frenck/python-wled/blob/803811d3e1fd2b9c63d1b6965be47fe2547fde4b/src/wled/wled.py#L252
Maybe this is it?

**Comment by ralong777** [comment]
i have the same problem, is there a fix?
