### ISSUE TITLE
Add support for CCT

### ISSUE THREAD

**Issue by haim-b** [frenck/python-wled#977]
# Problem/Motivation

WLED 0.13.0 added a new parameter in the API for changing the color temperature of the white color, for lights that support cold and warm whites. It's called "cct". See here https://kno.wled.ge/interfaces/json-api/
It will be nice to have a support for this.

## Expected behavior

Providing this ability will allow us to control the temperature of the white color.

## Actual behavior

I don't see any way to control the temperature of the white color.

## Steps to reproduce

Check out the current API.

## Proposed changes

In the segment method of the WLED class, add another "cct" argument. This argument should be translated to the "cct" parameter in the JSON that is sent to the WLED controller.

**Comment by frenck** [comment]
"color temperature of the white color"

So it isn't white?... it is amazing :D
